### ISSUE TITLE
Error: Unable to process command '::set-env

### ISSUE THREAD

**Issue by steadweb** [Terranovax/aws-ecr-deploy#8]
This is now disabled, as per https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by ear-dev** [comment]
This issue is a breaking issue.....  we will be unable to use this tool until fixed. Thanks.

**Comment by stephnr** [comment]
Hello @steadweb - sorry for the delay on this. I will need to switch away from Env Vars to the shared credentials style. Hopefully that wont take too long to implement/test.

**Comment by stephnr** [comment]
There is a new update now as `v1.1`. Can you please confirm this fixes your issue? @steadweb

**Comment by steadweb** [comment]
No worries @stephnr - appreciate the support. This has fixed the issue for me 🎉

**Comment by stephnr** [comment]
Perfect! I will go ahead and close the ticket 👌
